### ISSUE TITLE
debian /snap unsuported sdr-rtl

### ISSUE THREAD

**Issue by schghe** [albertodonato/rtlsdr-snap#1]
root@penguin:/home/schghe# cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@penguin:/home/schghe# sudo apt install snapd
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
snapd is already the newest version (2.49-1+deb11u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@penguin:/home/schghe# sudo snap install core
error: system does not fully support snapd: cannot mount squashfs image
       using "squashfs": mount: /tmp/sanity-mountpoint-113301822: mount
       failed: Operation not permitted.
root@penguin:/home/schghe# sudo snap install rtlsdr
error: system does not fully support snapd: cannot mount squashfs image
       using "squashfs": mount: /tmp/sanity-mountpoint-861381457: mount
       failed: Operation not permitted.
root@penguin:/home/schghe# 

hi,im geroge,im new in linux,i have a chromium OS,i cant install to use on this laptop sdr-rtl recever....i try everything.....powerwahs inclusiv....i cant install Flatpak ,error administrator rites....i will try more to finde a solution hire.tx very mouch for what you doing hire

schghe@yahoo.com

**Comment by albertodonato** [comment]
Did you follow the Debian-specific instructions on https://snapcraft.io/install/rtlsdr/debian to install and configure snapd?

This doesn't seem to be an issue specifically with the rtl-sdr snap, if you can't get snapd to work I'd suggest to ask for help on the [snapcraft forum](https://forum.snapcraft.io/)
